Features/juan lgc/password encryption
Laura-Romero/Proyecto-final-4Geeks-back pull request #11
Opened 2020-09-08 07:01 UTC by JuanLGC

Encriptacion de contraseña lista, falta:
- Comparacion entre la contraseña ingresada y la almacenada (ambas encriptadas o viceversa)

2020-09-14 10:53 UTC, JimenaEB requested changes

2020-09-14 10:53 UTC, JimenaEB commented on src/main.py
> +    print(b, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", user.password )
borra los prints

2020-09-14 10:53 UTC, JimenaEB commented on src/main.py
> +    b = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()),
los nombres de las variables deben ser claros

2020-09-15 20:05 UTC, JuanLGC commented on src/main.py
> +    b = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()),
Done! eran variables para probar, sorry, nunca la uso en el codigo 😥

2020-09-16 13:10 UTC, merged