Features/juan lgc/jwt
Laura-Romero/Proyecto-final-4Geeks-back pull request #12
Opened 2020-09-09 14:53 UTC by JuanLGC

2020-09-14 10:57 UTC, JimenaEB requested changes

2020-09-14 10:57 UTC, JimenaEB commented on src/main.py
> +app.config['SECRET_KEY'] = 'thisissecret'
si es secreto que no lo vea yo

2020-09-14 10:57 UTC, JimenaEB commented on src/main.py
> +from functools import wraps
el orden

2020-09-14 10:57 UTC, JimenaEB commented on src/main.py
> +app.config['JWT_SECRET_KEY'] = 'super-secret'  # Change this!
Duplicado?

2020-09-14 10:57 UTC, JimenaEB commented on src/main.py
>          return "Oops! Looks like something went wrong", 406
Y cuando va bien?

2020-09-14 10:57 UTC, JimenaEB commented on src/models.py
> +        print(user)
borra los prints

2020-09-15 20:10 UTC, JuanLGC commented on src/main.py
> +from functools import wraps
Done

2020-09-15 20:10 UTC, JuanLGC commented on src/main.py
> +app.config['JWT_SECRET_KEY'] = 'super-secret'  # Change this!
Deleted

2020-09-15 20:12 UTC, JuanLGC commented on src/main.py
>          return "Oops! Looks like something went wrong", 406
No sé si no he entendido, pero  justo arriba está la respuesta cuando es positivo :( 

if authentification == True:
        new_user.add_user(user_data)
        return "New user created", 200 👈🏼👈🏼👈🏼
    else:
        return "Oops! Looks like something went wrong", 406

2020-09-15 20:13 UTC, JuanLGC commented on src/models.py
> +        print(user)
Done

2020-09-16 13:17 UTC, merged